import os
os.environ['TKC_ONLY'] = 'True'
import scripts.app_helper as app

helper = app.Helper(ARGUMENTS)
helper.set_tkc_only().add_libs(['hello'])
helper.set_dll_def('src/hello.def').call(DefaultEnvironment)

SConsFiles = [
    'src/SConscript',
    'demos/SConscript',
    'tests/SConscript',
]

SConscript(SConsFiles)
